source 'https://rubygems.org'

gem 'bundler',        '~> 1.16'
gem 'rake'
gem 'minitest',       '~> 5.1'
gem 'activesupport',  '~> 5.1.0'
gem 'activerecord',   '~> 5.1.0'
gem 'mongoid',        '~> 6.1'
gem 'bson_ext'
gem 'coveralls'
gem 'sqlite3'
gem 'pry'
gem 'combustion'
